### ISSUE TITLE
lua: ./lualib/sprotodump.lua:1: module 'lfs' not found:

### ISSUE THREAD

**Issue by phynero** [zhangshiqian1214/spbtool#1]
lua: ./lualib/sprotodump.lua:1: module 'lfs' not found:

**Comment by phynero** [comment]
请问 mac下不可用吗

**Comment by zhangshiqian1214** [comment]
没有在mac下编译，编译一下就可以用

**Comment by phynero** [comment]
> 没有在mac下编译，编译一下就可以用

貌似没有可编译的工程

**Comment by zhangshiqian1214** [comment]
https://github.com/zhangshiqian1214/sprototool 这个项目下有工程, lfs也可以在网上下载源码编译

**Comment by phynero** [comment]
编译luafilesystem的时候 
luarocks install luafilesystem
报错cfg is not initialized, please run cfg.init() first


/Users/phynero/tools/lua/src/lua: /usr/local/share/lua/5.3/luarocks/fs.lua:79: cfg is not initialized, please run cfg.init() first
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.3/luarocks/fs.lua:80: in function 'luarocks.fs.init'
	/usr/local/share/lua/5.3/luarocks/cmd.lua:447: in function 'luarocks.cmd.run_command'
	...cal/lib/luarocks/rocks-5.3/luarocks/3.2.0-1/bin/luarocks:35: in main chunk
	[C]: in ?


看了下代码  没看懂要怎么做 应该在哪里cfg.init() 呢 ????  还是命令行里?


我是在mac下编译的  跟环境有关系吗

**Comment by zhangshiqian1214** [comment]
1.luafilesystem的地址https://github.com/keplerproject/luafilesystem, 编译出来是一个so文件，没有fs.lua
2.用luarocks编译报错，应该是/usr/local/share/lua/5.3/luarocks/fs.lua这个lua文件要用cfg.init()初始化
3. 建议直接用make编译生成动态库文件

**Comment by phynero** [comment]
谢谢 搞定了 但是这个是不是不支持小程序???  我看web上是ok的 但是小游戏上会报错

**Comment by phynero** [comment]
您好  我spb文件搞定了 本地test.js也跑通了  但是在ccc项目中 cc.loader.loadRes之后 我该怎么处理协议文件读取到的数据 直接let server = sproto.createNew(res); 会报错

sproto.js:102 Uncaught TypeError: stream.slice is not a function
    at struct_field (sproto.js:102)
    at create_from_bundle (sproto.js:362)
    at Object.t.createNew (sproto.js:1030)
    at HelloWorld.js:25
    at CCLoader.<anonymous> (CCLoader.js:493)
    at CCLoader.js:273
    at utils.js:79


还有一个问题是 这个东西支持微信吗 微信跟web还是有点区别

**Comment by zhangshiqian1214** [comment]
报错是你用法错了，sproto js版本是支持微信的，因为是纯js解析，不过spb文本要看微信是可以直接读还是只能用http获取

**Comment by phynero** [comment]
可能是我理解有问题吧  老哥方便加个联系方式指导一下吗😺

**Comment by phynero** [comment]
cc.loader.loadRes 加载spb获取到的数据是一个数组 里面有个_nativeAsset 估计是文件的内容 但是显示的是乱码数据  库中test加载出来的buffer却是二进制数据  请问我应该怎么处理一下_nativeAsset?

**Comment by phynero** [comment]
emmmmm 好像解决了...

生成的后缀.spb 改成.bin
然后 buffer = new Uint8Array(加载成功的res._buffer)
然后 let server = sproto.createNew(buffer); 就可以了...
